---
pipelines:
  Terraform: # baseline terraform pipeline
    group: Baseline
    locking: off
    materials:
      github:
        git: https://github.com/feedyard/baseline_tf.git
        branch: master
    stages: # list of stages in order
      - build: # name of stage
          clean_workspace: true
          jobs:
            slackTriggerBuild:
              tasks:
                - plugin:
                    options:
                      WebhookUrl: https://hooks.slack.com/services/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
                      ChannelType: Channel
                      Channel: deploy
                      DisplayName: Terraform Build Trigger
                      Title: Pipeline: Terraform trigger ${github
                      Message: The baseline terraform pipeline has detected a merge with the baeline repo and a build has been triggered
                      ColorType: none
                      IconOrEMoji:
                    configuration:
                      id: slack.task
                      version: 1

